package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/J-V-S-C/MindBox/graph/model"
)

// Roadmap is the resolver for the roadmap field.
func (r *categoryResolver) Roadmap(ctx context.Context, obj *model.Category) (*model.Roadmap, error) {
	panic(fmt.Errorf("not implemented: Roadmap - roadmap"))
}

// Tasks is the resolver for the tasks field.
func (r *categoryResolver) Tasks(ctx context.Context, obj *model.Category) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: Tasks - tasks"))
}

// CreateRoadmap is the resolver for the createRoadmap field.
func (r *mutationResolver) CreateRoadmap(ctx context.Context, input model.NewRoadmap) (*model.Roadmap, error) {
	var description string
	if input.Description != nil {
		description = *input.Description
	}

	roadmap, err := r.RoadmapDB.Create(input.Name, description)
	if err != nil {
		return nil, err
	}
	return &model.Roadmap{
		ID:          roadmap.ID,
		Name:        roadmap.Name,
		Description: &roadmap.Description,
	}, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	panic(fmt.Errorf("not implemented: CreateCategory - createCategory"))
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.NewTask) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: CreateTask - createTask"))
}

// ToggleTaskDone is the resolver for the toggleTaskDone field.
func (r *mutationResolver) ToggleTaskDone(ctx context.Context, id string) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: ToggleTaskDone - toggleTaskDone"))
}

// DeleteRoadmap is the resolver for the deleteRoadmap field.
func (r *mutationResolver) DeleteRoadmap(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteRoadmap - deleteRoadmap"))
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteCategory - deleteCategory"))
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTask - deleteTask"))
}

// Roadmaps is the resolver for the roadmaps field.
func (r *queryResolver) Roadmaps(ctx context.Context) ([]*model.Roadmap, error) {
	roadmaps, err := r.RoadmapDB.FindAll()
	if err != nil {
		return nil, err
	}
	var roadmapsModel []*model.Roadmap
	for _, roadmap := range roadmaps {
		roadmapsModel = append(roadmapsModel, &model.Roadmap{
			ID:          roadmap.ID,
			Name:        roadmap.Name,
			Description: &roadmap.Description,
		})
	}
	return roadmapsModel, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: Tasks - tasks"))
}

// DailyTasks is the resolver for the dailyTasks field.
func (r *queryResolver) DailyTasks(ctx context.Context) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: DailyTasks - dailyTasks"))
}

// PendingTasks is the resolver for the pendingTasks field.
func (r *queryResolver) PendingTasks(ctx context.Context, categoryID *string) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: PendingTasks - pendingTasks"))
}

// Categories is the resolver for the categories field.
func (r *roadmapResolver) Categories(ctx context.Context, obj *model.Roadmap) ([]*model.Category, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// IDDaily is the resolver for the idDaily field.
func (r *taskResolver) IDDaily(ctx context.Context, obj *model.Task) (bool, error) {
	panic(fmt.Errorf("not implemented: IDDaily - idDaily"))
}

// Category is the resolver for the category field.
func (r *taskResolver) Category(ctx context.Context, obj *model.Task) (*model.Category, error) {
	panic(fmt.Errorf("not implemented: Category - category"))
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Roadmap returns RoadmapResolver implementation.
func (r *Resolver) Roadmap() RoadmapResolver { return &roadmapResolver{r} }

// Task returns TaskResolver implementation.
func (r *Resolver) Task() TaskResolver { return &taskResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type roadmapResolver struct{ *Resolver }
type categoryResolver struct{ *Resolver }
type taskResolver struct{ *Resolver }
