package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/J-V-S-C/MindBox/graph/model"
)

// Roadmap is the resolver for the roadmap field.
func (r *categoryResolver) Roadmap(ctx context.Context, obj *model.Category) (*model.Roadmap, error) {
	category, err := r.CategoryDB.FindByID(obj.ID)
	if err != nil {
		return nil, err
	}

	res, err := r.RoadmapDB.FindByID(category.RoadmapID)
	if err != nil {
		return nil, err
	}

	return ToRoadmapModel(res), nil
}

// Tasks is the resolver for the tasks field.
func (r *categoryResolver) Tasks(ctx context.Context, obj *model.Category) ([]*model.Task, error) {
	res, err := r.TaskDB.FindByCategoryID(obj.ID, 100, 0)
	if err != nil {
		return nil, err
	}

	var tasks []*model.Task
	for _, task := range res {
		tasks = append(tasks, ToTaskModel(task))
	}
	return tasks, nil
}

// CreateRoadmap is the resolver for the createRoadmap field.
func (r *mutationResolver) CreateRoadmap(ctx context.Context, input model.NewRoadmap) (*model.Roadmap, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	res, err := r.RoadmapDB.Create(input.Name, description)
	if err != nil {
		return nil, err
	}

	return ToRoadmapModel(res), nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	res, err := r.CategoryDB.Create(input.Name, description, input.Lifetime, input.RoadmapID)
	if err != nil {
		return nil, err
	}

	return ToCategoryModel(res), nil
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.NewTask) (*model.Task, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}
	lifetime := ""
	if input.Lifetime != nil {
		lifetime = *input.Lifetime
	}

	res, err := r.TaskDB.Create(input.Name, description, input.IsDaily, lifetime, input.CategoryID)
	if err != nil {
		return nil, err
	}

	return ToTaskModel(res), nil
}

// UpdateRoadmap is the resolver for the updateRoadmap field.
func (r *mutationResolver) UpdateRoadmap(ctx context.Context, id string, input model.NewRoadmap) (*model.Roadmap, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	res, err := r.RoadmapDB.Update(id, input.Name, description)
	if err != nil {
		return nil, err
	}

	return ToRoadmapModel(res), nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input model.NewCategory) (*model.Category, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	res, err := r.CategoryDB.Update(id, input.Name, description, input.Lifetime)
	if err != nil {
		return nil, err
	}

	return ToCategoryModel(res), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.NewTask) (*model.Task, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}
	lifetime := ""
	if input.Lifetime != nil {
		lifetime = *input.Lifetime
	}

	res, err := r.TaskDB.Update(id, input.Name, description, input.IsDaily, lifetime)
	if err != nil {
		return nil, err
	}

	return ToTaskModel(res), nil
}

// ToggleTaskDone is the resolver for the toggleTaskDone field.
func (r *mutationResolver) ToggleTaskDone(ctx context.Context, id string) (*model.Task, error) {
	res, err := r.TaskDB.ToggleDone(id)
	if err != nil {
		return nil, err
	}

	return ToTaskModel(res), nil
}

// DeleteRoadmap is the resolver for the deleteRoadmap field.
func (r *mutationResolver) DeleteRoadmap(ctx context.Context, id string) (bool, error) {
	err := r.RoadmapDB.Delete(id)
	return err == nil, err
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	err := r.CategoryDB.Delete(id)
	return err == nil, err
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	err := r.TaskDB.Delete(id)
	return err == nil, err
}

// Roadmap is the resolver for the roadmap field.
func (r *queryResolver) Roadmap(ctx context.Context, id string) (*model.Roadmap, error) {
  res, err := r.RoadmapDB.FindByID(id)
  if err != nil {
    return nil, err
  }
  return ToRoadmapModel(res), nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
  res, err := r.CategoryDB.FindByID(id)
  if err != nil {
    return nil, err
  }
  return ToCategoryModel(res), nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
  res, err := r.TaskDB.FindByID(id)
  if err != nil {
    return nil, err
  }
  return ToTaskModel(res), nil
}

// Roadmaps is the resolver for the roadmaps field.
func (r *queryResolver) Roadmaps(ctx context.Context, limit int, offset int) ([]*model.Roadmap, error) {
	res, err := r.RoadmapDB.FindAll(limit, offset)
	if err != nil {
		return nil, err
	}

	var roadmaps []*model.Roadmap
	for _, roadmap := range res {
		roadmaps = append(roadmaps, ToRoadmapModel(roadmap))
	}
	return roadmaps, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, limit int, offset int) ([]*model.Category, error) {
	res, err := r.CategoryDB.FindAll(limit, offset)
	if err != nil {
		return nil, err
	}

	var categories []*model.Category
	for _, category := range res {
		categories = append(categories, ToCategoryModel(category))
	}
	return categories, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, limit int, offset int) ([]*model.Task, error) {
	res, err := r.TaskDB.FindAll(limit, offset)
	if err != nil {
		return nil, err
	}

	var tasks []*model.Task
	for _, task := range res {
		tasks = append(tasks, ToTaskModel(task))
	}
	return tasks, nil
}

// DailyTasks is the resolver for the dailyTasks field.
func (r *queryResolver) DailyTasks(ctx context.Context, limit int, offset int) ([]*model.Task, error) {
	res, err := r.TaskDB.FindDailyTasks(limit, offset)
	if err != nil {
		return nil, err
	}

	var tasks []*model.Task
	for _, task := range res {
		tasks = append(tasks, ToTaskModel(task))
	}
	return tasks, nil
}

// PendingTasks is the resolver for the pendingTasks field.
func (r *queryResolver) PendingTasks(ctx context.Context, categoryID string, limit int, offset int) ([]*model.Task, error) {
	res, err := r.TaskDB.FindPendingByCategoryID(categoryID, limit, offset)
	if err != nil {
		return nil, err
	}

	var tasks []*model.Task
	for _, task := range res {
		tasks = append(tasks, ToTaskModel(task))
	}
	return tasks, nil
}

// ExpiredTasks is the resolver for the expiredTasks field.
func (r *queryResolver) ExpiredTasks(ctx context.Context, limit int, offset int) ([]*model.Task, error) {
	res, err := r.TaskDB.FindExpiredTasks(limit, offset)
	if err != nil {
		return nil, err
	}

	var tasks []*model.Task
	for _, task := range res {
		tasks = append(tasks, ToTaskModel(task))
	}
	return tasks, nil
}

// Categories is the resolver for the categories field.
func (r *roadmapResolver) Categories(ctx context.Context, obj *model.Roadmap) ([]*model.Category, error) {
	res, err := r.CategoryDB.FindByRoadmapID(obj.ID)
	if err != nil {
		return nil, err
	}

	var categories []*model.Category
	for _, category := range res {
		categories = append(categories, ToCategoryModel(category))
	}
	return categories, nil
}

// Category is the resolver for the category field (Nested in Task).
func (r *taskResolver) Category(ctx context.Context, obj *model.Task) (*model.Category, error) {
	task, err := r.TaskDB.FindByID(obj.ID)
	if err != nil {
		return nil, err
	}

	res, err := r.CategoryDB.FindByID(task.CategoryID)
	if err != nil {
		return nil, err
	}

	return ToCategoryModel(res), nil
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Roadmap returns RoadmapResolver implementation.
func (r *Resolver) Roadmap() RoadmapResolver { return &roadmapResolver{r} }

// Task returns TaskResolver implementation.
func (r *Resolver) Task() TaskResolver { return &taskResolver{r} }

type categoryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type roadmapResolver struct{ *Resolver }
type taskResolver struct{ *Resolver }
