// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewCategory struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Lifetime    string  `json:"lifetime"`
	RoadmapID   string  `json:"roadmapId"`
}

type NewRoadmap struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type NewTask struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	IsDaily     bool    `json:"isDaily"`
	Lifetime    *string `json:"lifetime,omitempty"`
	CategoryID  string  `json:"categoryId"`
}

type Query struct {
}
